//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK.PEIS.Web.Service.SR_FactoryLayout {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_FactoryLayout.IFactoryLayoutWCFService")]
    public interface IFactoryLayoutWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactoryLayoutWCFService/GetAllPlant", ReplyAction="http://tempuri.org/IFactoryLayoutWCFService/GetAllPlantResponse")]
        System.Collections.Generic.List<HK.PEIS.DTO.DTO_TM_PLANT> GetAllPlant();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactoryLayoutWCFService/GetAllPlant", ReplyAction="http://tempuri.org/IFactoryLayoutWCFService/GetAllPlantResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HK.PEIS.DTO.DTO_TM_PLANT>> GetAllPlantAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFactoryLayoutWCFServiceChannel : HK.PEIS.Web.Service.SR_FactoryLayout.IFactoryLayoutWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FactoryLayoutWCFServiceClient : System.ServiceModel.ClientBase<HK.PEIS.Web.Service.SR_FactoryLayout.IFactoryLayoutWCFService>, HK.PEIS.Web.Service.SR_FactoryLayout.IFactoryLayoutWCFService {
        
        public FactoryLayoutWCFServiceClient() {
        }
        
        public FactoryLayoutWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FactoryLayoutWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactoryLayoutWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactoryLayoutWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<HK.PEIS.DTO.DTO_TM_PLANT> GetAllPlant() {
            return base.Channel.GetAllPlant();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HK.PEIS.DTO.DTO_TM_PLANT>> GetAllPlantAsync() {
            return base.Channel.GetAllPlantAsync();
        }
    }
}
