//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK.PEIS.Domain.Models
{
    using System;
    using System.ComponentModel.Composition;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [Export(typeof(DbContext))]
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_DEPARTMENT> TB_DEPARTMENT { get; set; }
        public virtual DbSet<TB_USERS> TB_USERS { get; set; }
        public virtual DbSet<TB_USERROLE> TB_USERROLE { get; set; }
        public virtual DbSet<TB_ROLE> TB_ROLE { get; set; }
        public virtual DbSet<TB_MENUROLE> TB_MENUROLE { get; set; }
        public virtual DbSet<TB_MENU> TB_MENU { get; set; }
    }
}
