//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK.PEIS.Domain.Models
{
    using HK.PEIS.Domain.BaseModel;
    using System;
    using System.Collections.Generic;

    public partial class TB_DEPARTMENT : AggregateRoot
    {
        public override string ToString()
        {
            return base.ToString();
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DEPARTMENT()
        {
            this.TB_USERS = new HashSet<TB_USERS>();
        }

        public int DEPARTMENT_ID { get; set; }
        public string DEPAREMENT_NAME { get; set; }
        public int PARENT_ID { get; set; }
        public int DEPAREMENT_LEVEL { get; set; }
        public int STATUS { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USERS> TB_USERS { get; set; }
    }
}
