//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK.PEIS.Domain.Models
{
    using HK.PEIS.Domain.BaseModel;
    using System;
    using System.Collections.Generic;

    public partial class TB_MENUROLE : IEntity
    {
        public int ID { get; set; }
        public int ROLE_ID { get; set; }
        public int MENU_ID { get; set; }
        public int ROLE_TYPE { get; set; }
        public int BUTTON_ID { get; set; }

        public virtual TB_ROLE TB_ROLE { get; set; }
        public virtual TB_MENU TB_MENU { get; set; }
    }
}
