//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK.PEIS.Domain.Models
{
    using HK.PEIS.Domain.BaseModel;
    using System;
    using System.Collections.Generic;

    public partial class TB_MENU : AggregateRoot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_MENU()
        {
            this.TB_MENUROLE = new HashSet<TB_MENUROLE>();
        }

        public int MENU_ID { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_URL { get; set; }
        public int PARENT_ID { get; set; }
        public int MENU_LEVEL { get; set; }
        public string STOP_ORDER { get; set; }
        public int STATUS { get; set; }
        public string REMARK { get; set; }
        public string MENU_ICO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MENUROLE> TB_MENUROLE { get; set; }
    }
}
